### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by alnf** [alnf/toxcore#30]
- [x] Fix key variable names - https://github.com/alnf/toxcore/issues/20
- [x] Join saved groups first via saved peers, second via DHT
- [x] Make announcements more reliable
- [x] Shorten chat_id
- [x] Securely exchange peer info on join
- [x] Keep group peer lists in sync/self healing
- [x] Prevent group splitting
- [x] Ensure integrity of group info on join (i.e. name, privacy state etc.)
- [x] Make chats 100% persistent. Rejoin empty group.
- [x] Fix peer join spam
- [ ] Write tests
- [x] Reduce packets length by removing signature key from packets (both groups and announcements)
- [x] Improve efficiency of encryption (only make symmetric key once and store it)
- [x] Do proper peer handshakes
- [ ] Make it work with TCP connections
- [x] Pad packets
- [x] Rewrite API
- [x] Use session keys for message encryption
- [x] Private/non-DHT groups
- [x] Founder powers
- [x] Moderation
- [x] Password protected groups
- [ ] Custom packets
- [x] Make topic settable for mods/founders only

**Comment by landswellsong** [comment]
- [ ] квадрат
- [ ] павукожирафа
- [ ] безвихідь
